version: '1.0'

services:
  main:
    container_name: oms-instore
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run start:dev
    ports:
      - 3001:3000